@startjson
{
    "_id": "MongoDB ObjectId",
    "name": "String",
    "website": "String",
    "last_scraped_at": "Date",
    "contact": { 
        "phone": "String",
        "email": "String",
        "address": "String"
    },
    "status": "String"
}
@endjson

